on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      cop_name:
        description: Pass cop name if you want to pick a specific cop.
        required: false
        type: string
      ignore:
        description: Check this with cop_name if you want to ignore a specific cop.
        required: false
        type: boolean

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: r7kamura/rubocop-todo-corrector@v0
        with:
          cop_name: ${{ inputs.cop_name }}
          # gh_pr_create_options: "--reviewer our-org/rubocop-reviewers"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ignore: ${{ inputs.ignore }}
          label: rubocop-todo-corrector
